### ISSUE TITLE
changing repo name?

### ISSUE THREAD

**Issue by bheavner** [UW-GAC/primed_example_notebooks#1]
Could we change this repo to something like GAC_AnVIL_example_notebooks and use it for examples applicable to GREGoR as well, or is it intended more to be shared with PRIMED analysts?

**Comment by mconomos** [comment]
I think we discussed this, but I think a separate repo for each consortium would be preferable for clarity. For example, we are going to link to this from the PRIMED website and GREGoR related notebooks might be confusing.

**Comment by bheavner** [comment]
I agree. @smgogarten I've made another repo at https://github.com/UW-GAC/gregor_example_notebooks and am closing this issue.
